version: "3"
services:
  bvb-database:
    image: postgres
    env_file:
      - ./.env
    container_name: bvb_db
    volumes:
      - ../database/:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  bvb-app:
    image: node:latest
    container_name: bvb_app
    depends_on: 
      - bvb-database
    links:
      - bvb-database
    environment: 
      WAIT_HOSTS: postgres:5432
    volumes:
      - ../:/var/www/app/api
    ports: 
      - ${NODE_PORT}:${NODE_PORT}
    working_dir: '/var/www/app/api'
    command: npm start